version: "3" # version del docker-compose que va a usar

services: # dentro de esta etiqueta se crean los servicios
    web: # nombre del servicio
        container_name: exampleapp # nombre del contenedor
        restart: always # si hay una falla siempre se va a reiniciar
        build: . # construye apartir del dockerfile encontrado en la ruta .
        ports: 
            - "5000:3000" # enlazar el puerto externo con el interto
        volumes: 
            - .:/usr/src/app # todo lo que esta en mi directorio de trabajo lo va a copiar dentro de /usr/src/app que es la ruta dentro del contenedor donde esta mi app, de manera dinamica
